name: Target Workflow

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: Jchinmay654/Master/.github/workflows/template.yml@main
        with:
          message: "Custom msg"


