name: Target Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import Template Workflow
        uses: Jchinmay654/Master/.github/workflows/template.yml@{branch-or-tag}
        with:
          message: "Custom message"
      
   



